version: 3

server: https://app.fossa.com

project:
  id: github.com/witlox/sovra
  name: sovra

analyze:
  modules:
    - path: .
      type: gomod

# Allow copyleft licenses used by transitive dependencies
# MPL-2.0: HashiCorp Vault API - weak copyleft, only affects modified files
# LGPL-2.1: OpenTelemetry instrumentation - allows linking without copyleft
vendoredDependencies:
  forceRescans: false

paths:
  exclude:
    - tests/
    - docs/
    - infrastructure/
    - vendor/
