#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - apt-transport-https
  - ca-certificates

runcmd:
  - |
    # Wait for server to be ready
    until curl -k -s ${server_url}/healthz > /dev/null 2>&1; do
      echo "Waiting for K3s server..."
      sleep 10
    done
    
    # Install K3s agent
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="${k3s_version}" sh -s - agent \
      --server ${server_url} \
      --token "${k3s_token}" \
      --node-ip ${node_ip} \
      --flannel-iface ens10
